platform :ios, "8.1"
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

target 'VetX' do
  xcodeproj 'VetX'
  pod 'TwilioConversationsClient'
  pod 'BlocksKit'
  pod 'Google/Analytics'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'JSQMessagesViewController'
  pod 'Braintree'
  pod 'Braintree/Apple-Pay'
  pod 'Fabric'
  pod 'Optimizely-iOS-SDK'
  pod 'Crashlytics'
  pod 'DGActivityIndicatorView'
  pod 'AFNetworking'
  pod 'Rollout.io'
  pod 'Apptimize'
  pod 'Masonry'
  pod 'Realm'
  pod 'RBQFetchedResultsController'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'M13Checkbox', '~> 1.2.0'
  pod 'IQKeyboardManager'
  pod 'Mantle'
  pod 'RSKKeyboardAnimationObserver'
  pod 'SCLAlertView-Objective-C'
  pod 'RMDateSelectionViewController'
  pod 'JTCalendar'
  pod 'pop'
  pod 'TTTAttributedLabel'
  pod 'AnimatedGIFImageSerialization'
  pod 'MWPhotoBrowser'
  pod 'DateTools'
end
